// Code generated by MockGen. DO NOT EDIT.
// Source: service/csv/csv.go

// Package mock is a generated GoMock package.
package mock

import (
	model "pokeapi/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNewCsvService is a mock of NewCsvService interface.
type MockNewCsvService struct {
	ctrl     *gomock.Controller
	recorder *MockNewCsvServiceMockRecorder
}

// MockNewCsvServiceMockRecorder is the mock recorder for MockNewCsvService.
type MockNewCsvServiceMockRecorder struct {
	mock *MockNewCsvService
}

// NewMockNewCsvService creates a new mock instance.
func NewMockNewCsvService(ctrl *gomock.Controller) *MockNewCsvService {
	mock := &MockNewCsvService{ctrl: ctrl}
	mock.recorder = &MockNewCsvServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNewCsvService) EXPECT() *MockNewCsvServiceMockRecorder {
	return m.recorder
}

// GetPokemon mocks base method.
func (m *MockNewCsvService) GetPokemon(pokemonId int) (model.Pokemon, *model.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPokemon", pokemonId)
	ret0, _ := ret[0].(model.Pokemon)
	ret1, _ := ret[1].(*model.Error)
	return ret0, ret1
}

// GetPokemon indicates an expected call of GetPokemon.
func (mr *MockNewCsvServiceMockRecorder) GetPokemon(pokemonId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPokemon", reflect.TypeOf((*MockNewCsvService)(nil).GetPokemon), pokemonId)
}

// GetPokemons mocks base method.
func (m *MockNewCsvService) GetPokemons() ([]model.Pokemon, *model.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPokemons")
	ret0, _ := ret[0].([]model.Pokemon)
	ret1, _ := ret[1].(*model.Error)
	return ret0, ret1
}

// GetPokemons indicates an expected call of GetPokemons.
func (mr *MockNewCsvServiceMockRecorder) GetPokemons() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPokemons", reflect.TypeOf((*MockNewCsvService)(nil).GetPokemons))
}

// GetPokemonsConcurrently mocks base method.
func (m *MockNewCsvService) GetPokemonsConcurrently(typeNumber string, items, itemsPerWorker int) ([]model.Pokemon, *model.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPokemonsConcurrently", typeNumber, items, itemsPerWorker)
	ret0, _ := ret[0].([]model.Pokemon)
	ret1, _ := ret[1].(*model.Error)
	return ret0, ret1
}

// GetPokemonsConcurrently indicates an expected call of GetPokemonsConcurrently.
func (mr *MockNewCsvServiceMockRecorder) GetPokemonsConcurrently(typeNumber, items, itemsPerWorker interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPokemonsConcurrently", reflect.TypeOf((*MockNewCsvService)(nil).GetPokemonsConcurrently), typeNumber, items, itemsPerWorker)
}

// SavePokemons mocks base method.
func (m *MockNewCsvService) SavePokemons(arg0 *[]model.SinglePokeExternal) *model.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePokemons", arg0)
	ret0, _ := ret[0].(*model.Error)
	return ret0
}

// SavePokemons indicates an expected call of SavePokemons.
func (mr *MockNewCsvServiceMockRecorder) SavePokemons(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePokemons", reflect.TypeOf((*MockNewCsvService)(nil).SavePokemons), arg0)
}
