// Code generated by MockGen. DO NOT EDIT.
// Source: router/router.go

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// GetExternalPokemons mocks base method.
func (m *MockController) GetExternalPokemons(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetExternalPokemons", w, r)
}

// GetExternalPokemons indicates an expected call of GetExternalPokemons.
func (mr *MockControllerMockRecorder) GetExternalPokemons(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalPokemons", reflect.TypeOf((*MockController)(nil).GetExternalPokemons), w, r)
}

// GetLocalPokemon mocks base method.
func (m *MockController) GetLocalPokemon(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetLocalPokemon", w, r)
}

// GetLocalPokemon indicates an expected call of GetLocalPokemon.
func (mr *MockControllerMockRecorder) GetLocalPokemon(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalPokemon", reflect.TypeOf((*MockController)(nil).GetLocalPokemon), w, r)
}

// GetLocalPokemons mocks base method.
func (m *MockController) GetLocalPokemons(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetLocalPokemons", w, r)
}

// GetLocalPokemons indicates an expected call of GetLocalPokemons.
func (mr *MockControllerMockRecorder) GetLocalPokemons(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalPokemons", reflect.TypeOf((*MockController)(nil).GetLocalPokemons), w, r)
}
