// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jesus-mata/academy-go-q12021/infrastructure/newsapi (interfaces: NewsApiClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/jesus-mata/academy-go-q12021/infrastructure/dto"
)

// MockNewsApiClient is a mock of NewsApiClient interface.
type MockNewsApiClient struct {
	ctrl     *gomock.Controller
	recorder *MockNewsApiClientMockRecorder
}

// MockNewsApiClientMockRecorder is the mock recorder for MockNewsApiClient.
type MockNewsApiClientMockRecorder struct {
	mock *MockNewsApiClient
}

// NewMockNewsApiClient creates a new mock instance.
func NewMockNewsApiClient(ctrl *gomock.Controller) *MockNewsApiClient {
	mock := &MockNewsApiClient{ctrl: ctrl}
	mock.recorder = &MockNewsApiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNewsApiClient) EXPECT() *MockNewsApiClientMockRecorder {
	return m.recorder
}

// GetCurrentNews mocks base method.
func (m *MockNewsApiClient) GetCurrentNews() ([]dto.NewItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentNews")
	ret0, _ := ret[0].([]dto.NewItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentNews indicates an expected call of GetCurrentNews.
func (mr *MockNewsApiClientMockRecorder) GetCurrentNews() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentNews", reflect.TypeOf((*MockNewsApiClient)(nil).GetCurrentNews))
}
